spring:
  datasource:
    password: flamingo
    url: jdbc:mysql://
    username: root
  mail:  # qq邮件发送
    host: smtp.qq.com
    password: xxxxxxxxxx
    username: 1952789737@qq.com
    port: 465


server:
  servlet:
    context-path: /api
  port: 7050
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.animal.product.controller


email:
  email-from: 1952789737@qq.com
  subject: ${spring.mail.username}


